import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request) {
  try {
    const {
      name,
      email,
      phone,
      payment_method,
      card_digits,
      invoice_num,
      order_date,
      refund_reason,
      message,
    } = await request.json();
    const transporter = nodemailer.createTransport({
      service: "gmail",
      host: "smtp.gmail.com",
      port: 587,
      secure: true,
      auth: {
        user: "developer@infinitimediainc.com",
        pass: "wikkfldsnncrculb",
      },
    });
    const mailOptions = {
      from: "developer@infinitimediainc.com",
      to: "finance@bitswits.co",
      subject: `New Lead Generated By Infiniti Media Inc`,
      html: `<div style="width:100%;height:100%;padding:1rem;background-color: #efefef;">
                <div style="display:flex; align-items: center;">
                    <h4>Name : ${name}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Email : ${email}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Phone : ${phone}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Payment Method : ${payment_method}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Card Digits : ${card_digits}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Invoice Number : ${invoice_num}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Order Date : ${order_date}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Refund Reason : ${refund_reason}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Message : ${message}</h4>
                </div>
            </div>`,
    };
    await transporter.sendMail(mailOptions);
    return NextResponse.json({ mesaage: "Email sent successfully", status: 200 });
  } catch (error) {
    return NextResponse.json({ mesaage: "Failed to sent Email", status: 500 });
  }
}
